/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/c6a256b3-ef82-4486-b6b6-9d3beb58dcf3 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int ir_remote;
  bool microphone;
  bool ultrasonic;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"



void setup() {
  // Initialize serial and wait for port to open:
  
  pinMode(LED_BUILTIN, OUTPUT);      // set LED pin as output
  digitalWrite(LED_BUILTIN, LOW);    // switch off LED pin

  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  while (Serial1.available() >= 0) {
    char receivedData = Serial1.read();   // read one byte from serial buffer and save to receivedData

    ultrasonic = (receivedData & 0b10000000) ? 1 : 0;
    microphone = (receivedData & 0b01000000) ? 1 : 0;
    ir_remote = (receivedData & 0b00111000) >> 3;

    if (ultrasonic == 1) {
      digitalWrite(LED_BUILTIN, HIGH); // switch LED On0
    }
    else if (ultrasonic == 0) {
      digitalWrite(LED_BUILTIN, LOW);  // switch LED Off
    }
  }
  
}


/*
  Since Reading is READ_WRITE variable, onReadingChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onReadingChange()  {
  // Add your code here to act upon Reading change
}


/*
  Since Ultrasonic is READ_WRITE variable, onUltrasonicChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onUltrasonicChange()  {
  // Add your code here to act upon Ultrasonic change
}

/*
  Since Microphone is READ_WRITE variable, onMicrophoneChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMicrophoneChange()  {
  // Add your code here to act upon Microphone change
}

/*
  Since IrRemote is READ_WRITE variable, onIrRemoteChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIrRemoteChange()  {
  // Add your code here to act upon IrRemote change
}
